/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Timestamp = IDL.Int;
export const ChallengeCategory = IDL.Variant({
  'Singing' : IDL.Null,
  'Cooking' : IDL.Null,
  'Gaming' : IDL.Null,
  'Mimicry' : IDL.Null,
  'Coding' : IDL.Null,
});
export const CreateChallengeInput = IDL.Record({
  'title' : IDL.Text,
  'endDate' : Timestamp,
  'category' : ChallengeCategory,
  'rules' : IDL.Text,
  'startDate' : Timestamp,
});
export const ChallengeId = IDL.Nat;
export const SubmissionId = IDL.Nat;
export const Challenge = IDL.Record({
  'id' : ChallengeId,
  'title' : IDL.Text,
  'endDate' : Timestamp,
  'winnerId' : IDL.Opt(SubmissionId),
  'category' : ChallengeCategory,
  'rules' : IDL.Text,
  'startDate' : Timestamp,
});
export const UserId = IDL.Principal;
export const VideoEffect = IDL.Variant({
  'Professional' : IDL.Null,
  'Cartoon' : IDL.Null,
  'Cinematic' : IDL.Null,
});
export const Submission = IDL.Record({
  'id' : SubmissionId,
  'voteCount' : IDL.Nat,
  'creatorId' : UserId,
  'submittedAt' : Timestamp,
  'effect' : IDL.Opt(VideoEffect),
  'challengeId' : ChallengeId,
  'videoUrl' : IDL.Text,
});
export const Rank = IDL.Variant({
  'Gold' : IDL.Null,
  'Platinum' : IDL.Null,
  'Bronze' : IDL.Null,
  'Silver' : IDL.Null,
});
export const User = IDL.Record({
  'id' : UserId,
  'bio' : IDL.Text,
  'referralCode' : IDL.Text,
  'videoCount' : IDL.Nat,
  'coinBalance' : IDL.Nat,
  'city' : IDL.Text,
  'createdAt' : Timestamp,
  'rank' : Rank,
  'referralCount' : IDL.Nat,
  'creatorName' : IDL.Text,
  'district' : IDL.Text,
  'totalVotesReceived' : IDL.Nat,
  'hasLegendTag' : IDL.Bool,
  'isUnlocked' : IDL.Bool,
});
export const ReferralInfo = IDL.Record({
  'referralCode' : IDL.Text,
  'referralCount' : IDL.Nat,
  'isUnlocked' : IDL.Bool,
});
export const RegisterInput = IDL.Record({
  'bio' : IDL.Text,
  'referralCode' : IDL.Opt(IDL.Text),
  'city' : IDL.Text,
  'creatorName' : IDL.Text,
  'district' : IDL.Text,
});
export const SubmitVideoInput = IDL.Record({
  'effect' : IDL.Opt(VideoEffect),
  'challengeId' : ChallengeId,
  'videoUrl' : IDL.Text,
});

export const idlService = IDL.Service({
  'adminSeedData' : IDL.Func([], [IDL.Text], []),
  'castVote' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'claimOwnership' : IDL.Func([], [IDL.Bool], []),
  'createChallenge' : IDL.Func([CreateChallengeInput], [Challenge], []),
  'finalizeChallenge' : IDL.Func([ChallengeId], [IDL.Opt(SubmissionId)], []),
  'getChallenge' : IDL.Func([ChallengeId], [IDL.Opt(Challenge)], ['query']),
  'getChallengeLeaderboard' : IDL.Func(
      [ChallengeId],
      [IDL.Vec(Submission)],
      ['query'],
    ),
  'getMyProfile' : IDL.Func([], [IDL.Opt(User)], []),
  'getOwner' : IDL.Func([], [IDL.Principal], ['query']),
  'getReferralInfo' : IDL.Func([], [IDL.Opt(ReferralInfo)], []),
  'getRemainingCoins' : IDL.Func([], [IDL.Nat], []),
  'getUserById' : IDL.Func([IDL.Principal], [IDL.Opt(User)], ['query']),
  'getVoteCount' : IDL.Func([IDL.Nat], [IDL.Nat], ['query']),
  'listChallenges' : IDL.Func([], [IDL.Vec(Challenge)], ['query']),
  'listUsersByLocation' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Text)],
      [IDL.Vec(User)],
      ['query'],
    ),
  'registerUser' : IDL.Func([RegisterInput], [User], []),
  'submitVideo' : IDL.Func([SubmitVideoInput], [Submission], []),
  'trackReferral' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'updateMyProfile' : IDL.Func(
      [
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
      ],
      [User],
      [],
    ),
  'validateReferralCode' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(IDL.Principal)],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Timestamp = IDL.Int;
  const ChallengeCategory = IDL.Variant({
    'Singing' : IDL.Null,
    'Cooking' : IDL.Null,
    'Gaming' : IDL.Null,
    'Mimicry' : IDL.Null,
    'Coding' : IDL.Null,
  });
  const CreateChallengeInput = IDL.Record({
    'title' : IDL.Text,
    'endDate' : Timestamp,
    'category' : ChallengeCategory,
    'rules' : IDL.Text,
    'startDate' : Timestamp,
  });
  const ChallengeId = IDL.Nat;
  const SubmissionId = IDL.Nat;
  const Challenge = IDL.Record({
    'id' : ChallengeId,
    'title' : IDL.Text,
    'endDate' : Timestamp,
    'winnerId' : IDL.Opt(SubmissionId),
    'category' : ChallengeCategory,
    'rules' : IDL.Text,
    'startDate' : Timestamp,
  });
  const UserId = IDL.Principal;
  const VideoEffect = IDL.Variant({
    'Professional' : IDL.Null,
    'Cartoon' : IDL.Null,
    'Cinematic' : IDL.Null,
  });
  const Submission = IDL.Record({
    'id' : SubmissionId,
    'voteCount' : IDL.Nat,
    'creatorId' : UserId,
    'submittedAt' : Timestamp,
    'effect' : IDL.Opt(VideoEffect),
    'challengeId' : ChallengeId,
    'videoUrl' : IDL.Text,
  });
  const Rank = IDL.Variant({
    'Gold' : IDL.Null,
    'Platinum' : IDL.Null,
    'Bronze' : IDL.Null,
    'Silver' : IDL.Null,
  });
  const User = IDL.Record({
    'id' : UserId,
    'bio' : IDL.Text,
    'referralCode' : IDL.Text,
    'videoCount' : IDL.Nat,
    'coinBalance' : IDL.Nat,
    'city' : IDL.Text,
    'createdAt' : Timestamp,
    'rank' : Rank,
    'referralCount' : IDL.Nat,
    'creatorName' : IDL.Text,
    'district' : IDL.Text,
    'totalVotesReceived' : IDL.Nat,
    'hasLegendTag' : IDL.Bool,
    'isUnlocked' : IDL.Bool,
  });
  const ReferralInfo = IDL.Record({
    'referralCode' : IDL.Text,
    'referralCount' : IDL.Nat,
    'isUnlocked' : IDL.Bool,
  });
  const RegisterInput = IDL.Record({
    'bio' : IDL.Text,
    'referralCode' : IDL.Opt(IDL.Text),
    'city' : IDL.Text,
    'creatorName' : IDL.Text,
    'district' : IDL.Text,
  });
  const SubmitVideoInput = IDL.Record({
    'effect' : IDL.Opt(VideoEffect),
    'challengeId' : ChallengeId,
    'videoUrl' : IDL.Text,
  });
  
  return IDL.Service({
    'adminSeedData' : IDL.Func([], [IDL.Text], []),
    'castVote' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'claimOwnership' : IDL.Func([], [IDL.Bool], []),
    'createChallenge' : IDL.Func([CreateChallengeInput], [Challenge], []),
    'finalizeChallenge' : IDL.Func([ChallengeId], [IDL.Opt(SubmissionId)], []),
    'getChallenge' : IDL.Func([ChallengeId], [IDL.Opt(Challenge)], ['query']),
    'getChallengeLeaderboard' : IDL.Func(
        [ChallengeId],
        [IDL.Vec(Submission)],
        ['query'],
      ),
    'getMyProfile' : IDL.Func([], [IDL.Opt(User)], []),
    'getOwner' : IDL.Func([], [IDL.Principal], ['query']),
    'getReferralInfo' : IDL.Func([], [IDL.Opt(ReferralInfo)], []),
    'getRemainingCoins' : IDL.Func([], [IDL.Nat], []),
    'getUserById' : IDL.Func([IDL.Principal], [IDL.Opt(User)], ['query']),
    'getVoteCount' : IDL.Func([IDL.Nat], [IDL.Nat], ['query']),
    'listChallenges' : IDL.Func([], [IDL.Vec(Challenge)], ['query']),
    'listUsersByLocation' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Text)],
        [IDL.Vec(User)],
        ['query'],
      ),
    'registerUser' : IDL.Func([RegisterInput], [User], []),
    'submitVideo' : IDL.Func([SubmitVideoInput], [Submission], []),
    'trackReferral' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'updateMyProfile' : IDL.Func(
        [
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
        ],
        [User],
        [],
      ),
    'validateReferralCode' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(IDL.Principal)],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };