/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Challenge {
  'id' : ChallengeId,
  'title' : string,
  'endDate' : Timestamp,
  'winnerId' : [] | [SubmissionId],
  'category' : ChallengeCategory,
  'rules' : string,
  'startDate' : Timestamp,
}
export type ChallengeCategory = { 'Singing' : null } |
  { 'Cooking' : null } |
  { 'Gaming' : null } |
  { 'Mimicry' : null } |
  { 'Coding' : null };
export type ChallengeId = bigint;
export interface CreateChallengeInput {
  'title' : string,
  'endDate' : Timestamp,
  'category' : ChallengeCategory,
  'rules' : string,
  'startDate' : Timestamp,
}
export type Rank = { 'Gold' : null } |
  { 'Platinum' : null } |
  { 'Bronze' : null } |
  { 'Silver' : null };
export interface ReferralInfo {
  'referralCode' : string,
  'referralCount' : bigint,
  'isUnlocked' : boolean,
}
export interface RegisterInput {
  'bio' : string,
  'referralCode' : [] | [string],
  'city' : string,
  'creatorName' : string,
  'district' : string,
}
export interface Submission {
  'id' : SubmissionId,
  'voteCount' : bigint,
  'creatorId' : UserId,
  'submittedAt' : Timestamp,
  'effect' : [] | [VideoEffect],
  'challengeId' : ChallengeId,
  'videoUrl' : string,
}
export type SubmissionId = bigint;
export interface SubmitVideoInput {
  'effect' : [] | [VideoEffect],
  'challengeId' : ChallengeId,
  'videoUrl' : string,
}
export type Timestamp = bigint;
export interface User {
  'id' : UserId,
  'bio' : string,
  'referralCode' : string,
  'videoCount' : bigint,
  'coinBalance' : bigint,
  'city' : string,
  'createdAt' : Timestamp,
  'rank' : Rank,
  'referralCount' : bigint,
  'creatorName' : string,
  'district' : string,
  'totalVotesReceived' : bigint,
  'hasLegendTag' : boolean,
  'isUnlocked' : boolean,
}
export type UserId = Principal;
export type VideoEffect = { 'Professional' : null } |
  { 'Cartoon' : null } |
  { 'Cinematic' : null };
export interface _SERVICE {
  'adminSeedData' : ActorMethod<[], string>,
  'castVote' : ActorMethod<
    [bigint, bigint],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'claimOwnership' : ActorMethod<[], boolean>,
  'createChallenge' : ActorMethod<[CreateChallengeInput], Challenge>,
  'finalizeChallenge' : ActorMethod<[ChallengeId], [] | [SubmissionId]>,
  'getChallenge' : ActorMethod<[ChallengeId], [] | [Challenge]>,
  'getChallengeLeaderboard' : ActorMethod<[ChallengeId], Array<Submission>>,
  'getMyProfile' : ActorMethod<[], [] | [User]>,
  'getOwner' : ActorMethod<[], Principal>,
  'getReferralInfo' : ActorMethod<[], [] | [ReferralInfo]>,
  'getRemainingCoins' : ActorMethod<[], bigint>,
  'getUserById' : ActorMethod<[Principal], [] | [User]>,
  'getVoteCount' : ActorMethod<[bigint], bigint>,
  'listChallenges' : ActorMethod<[], Array<Challenge>>,
  'listUsersByLocation' : ActorMethod<[string, [] | [string]], Array<User>>,
  'registerUser' : ActorMethod<[RegisterInput], User>,
  'submitVideo' : ActorMethod<[SubmitVideoInput], Submission>,
  'trackReferral' : ActorMethod<[string], { 'ok' : null } | { 'err' : string }>,
  'updateMyProfile' : ActorMethod<
    [[] | [string], [] | [string], [] | [string], [] | [string]],
    User
  >,
  'validateReferralCode' : ActorMethod<[string], [] | [Principal]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];