/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Timestamp = bigint;
export interface CreateChallengeInput {
    title: string;
    endDate: Timestamp;
    category: ChallengeCategory;
    rules: string;
    startDate: Timestamp;
}
export interface User {
    id: UserId;
    bio: string;
    referralCode: string;
    videoCount: bigint;
    coinBalance: bigint;
    city: string;
    createdAt: Timestamp;
    rank: Rank;
    referralCount: bigint;
    creatorName: string;
    district: string;
    totalVotesReceived: bigint;
    hasLegendTag: boolean;
    isUnlocked: boolean;
}
export type ChallengeId = bigint;
export interface SubmitVideoInput {
    effect?: VideoEffect;
    challengeId: ChallengeId;
    videoUrl: string;
}
export interface Challenge {
    id: ChallengeId;
    title: string;
    endDate: Timestamp;
    winnerId?: SubmissionId;
    category: ChallengeCategory;
    rules: string;
    startDate: Timestamp;
}
export type SubmissionId = bigint;
export type UserId = Principal;
export interface RegisterInput {
    bio: string;
    referralCode?: string;
    city: string;
    creatorName: string;
    district: string;
}
export interface ReferralInfo {
    referralCode: string;
    referralCount: bigint;
    isUnlocked: boolean;
}
export interface Submission {
    id: SubmissionId;
    voteCount: bigint;
    creatorId: UserId;
    submittedAt: Timestamp;
    effect?: VideoEffect;
    challengeId: ChallengeId;
    videoUrl: string;
}
export enum ChallengeCategory {
    Singing = "Singing",
    Cooking = "Cooking",
    Gaming = "Gaming",
    Mimicry = "Mimicry",
    Coding = "Coding"
}
export enum Rank {
    Gold = "Gold",
    Platinum = "Platinum",
    Bronze = "Bronze",
    Silver = "Silver"
}
export enum VideoEffect {
    Professional = "Professional",
    Cartoon = "Cartoon",
    Cinematic = "Cinematic"
}
export interface backendInterface {
    adminSeedData(): Promise<string>;
    castVote(submissionId: bigint, challengeId: bigint): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    claimOwnership(): Promise<boolean>;
    createChallenge(input: CreateChallengeInput): Promise<Challenge>;
    finalizeChallenge(challengeId: ChallengeId): Promise<SubmissionId | null>;
    getChallenge(id: ChallengeId): Promise<Challenge | null>;
    getChallengeLeaderboard(challengeId: ChallengeId): Promise<Array<Submission>>;
    getMyProfile(): Promise<User | null>;
    getOwner(): Promise<Principal>;
    getReferralInfo(): Promise<ReferralInfo | null>;
    getRemainingCoins(): Promise<bigint>;
    getUserById(userId: Principal): Promise<User | null>;
    getVoteCount(submissionId: bigint): Promise<bigint>;
    listChallenges(): Promise<Array<Challenge>>;
    listUsersByLocation(city: string, district: string | null): Promise<Array<User>>;
    registerUser(input: RegisterInput): Promise<User>;
    submitVideo(input: SubmitVideoInput): Promise<Submission>;
    trackReferral(referralCode: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    updateMyProfile(creatorName: string | null, bio: string | null, city: string | null, district: string | null): Promise<User>;
    validateReferralCode(code: string): Promise<Principal | null>;
}
import type { Challenge as _Challenge, ChallengeCategory as _ChallengeCategory, ChallengeId as _ChallengeId, CreateChallengeInput as _CreateChallengeInput, Rank as _Rank, ReferralInfo as _ReferralInfo, RegisterInput as _RegisterInput, Submission as _Submission, SubmissionId as _SubmissionId, SubmitVideoInput as _SubmitVideoInput, Timestamp as _Timestamp, User as _User, UserId as _UserId, VideoEffect as _VideoEffect } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async adminSeedData(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.adminSeedData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminSeedData();
            return result;
        }
    }
    async castVote(arg0: bigint, arg1: bigint): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.castVote(arg0, arg1);
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.castVote(arg0, arg1);
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async claimOwnership(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.claimOwnership();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.claimOwnership();
            return result;
        }
    }
    async createChallenge(arg0: CreateChallengeInput): Promise<Challenge> {
        if (this.processError) {
            try {
                const result = await this.actor.createChallenge(to_candid_CreateChallengeInput_n2(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Challenge_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createChallenge(to_candid_CreateChallengeInput_n2(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Challenge_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async finalizeChallenge(arg0: ChallengeId): Promise<SubmissionId | null> {
        if (this.processError) {
            try {
                const result = await this.actor.finalizeChallenge(arg0);
                return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.finalizeChallenge(arg0);
            return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getChallenge(arg0: ChallengeId): Promise<Challenge | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getChallenge(arg0);
                return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChallenge(arg0);
            return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getChallengeLeaderboard(arg0: ChallengeId): Promise<Array<Submission>> {
        if (this.processError) {
            try {
                const result = await this.actor.getChallengeLeaderboard(arg0);
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChallengeLeaderboard(arg0);
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyProfile(): Promise<User | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyProfile();
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyProfile();
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOwner(): Promise<Principal> {
        if (this.processError) {
            try {
                const result = await this.actor.getOwner();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOwner();
            return result;
        }
    }
    async getReferralInfo(): Promise<ReferralInfo | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getReferralInfo();
                return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReferralInfo();
            return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRemainingCoins(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getRemainingCoins();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRemainingCoins();
            return result;
        }
    }
    async getUserById(arg0: Principal): Promise<User | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserById(arg0);
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserById(arg0);
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVoteCount(arg0: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getVoteCount(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVoteCount(arg0);
            return result;
        }
    }
    async listChallenges(): Promise<Array<Challenge>> {
        if (this.processError) {
            try {
                const result = await this.actor.listChallenges();
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listChallenges();
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async listUsersByLocation(arg0: string, arg1: string | null): Promise<Array<User>> {
        if (this.processError) {
            try {
                const result = await this.actor.listUsersByLocation(arg0, to_candid_opt_n25(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listUsersByLocation(arg0, to_candid_opt_n25(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async registerUser(arg0: RegisterInput): Promise<User> {
        if (this.processError) {
            try {
                const result = await this.actor.registerUser(to_candid_RegisterInput_n27(this._uploadFile, this._downloadFile, arg0));
                return from_candid_User_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerUser(to_candid_RegisterInput_n27(this._uploadFile, this._downloadFile, arg0));
            return from_candid_User_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitVideo(arg0: SubmitVideoInput): Promise<Submission> {
        if (this.processError) {
            try {
                const result = await this.actor.submitVideo(to_candid_SubmitVideoInput_n29(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Submission_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitVideo(to_candid_SubmitVideoInput_n29(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Submission_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async trackReferral(arg0: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.trackReferral(arg0);
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.trackReferral(arg0);
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateMyProfile(arg0: string | null, arg1: string | null, arg2: string | null, arg3: string | null): Promise<User> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMyProfile(to_candid_opt_n25(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n25(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n25(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n25(this._uploadFile, this._downloadFile, arg3));
                return from_candid_User_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMyProfile(to_candid_opt_n25(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n25(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n25(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n25(this._uploadFile, this._downloadFile, arg3));
            return from_candid_User_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async validateReferralCode(arg0: string): Promise<Principal | null> {
        if (this.processError) {
            try {
                const result = await this.actor.validateReferralCode(arg0);
                return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.validateReferralCode(arg0);
            return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_ChallengeCategory_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ChallengeCategory): ChallengeCategory {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_Challenge_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Challenge): Challenge {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_Rank_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Rank): Rank {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_Submission_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Submission): Submission {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_User_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _User): User {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_VideoEffect_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VideoEffect): VideoEffect {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Challenge]): Challenge | null {
    return value.length === 0 ? null : from_candid_Challenge_n6(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_VideoEffect]): VideoEffect | null {
    return value.length === 0 ? null : from_candid_VideoEffect_n16(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_User]): User | null {
    return value.length === 0 ? null : from_candid_User_n19(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ReferralInfo]): ReferralInfo | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SubmissionId]): SubmissionId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _SubmissionId;
    voteCount: bigint;
    creatorId: _UserId;
    submittedAt: _Timestamp;
    effect: [] | [_VideoEffect];
    challengeId: _ChallengeId;
    videoUrl: string;
}): {
    id: SubmissionId;
    voteCount: bigint;
    creatorId: UserId;
    submittedAt: Timestamp;
    effect?: VideoEffect;
    challengeId: ChallengeId;
    videoUrl: string;
} {
    return {
        id: value.id,
        voteCount: value.voteCount,
        creatorId: value.creatorId,
        submittedAt: value.submittedAt,
        effect: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.effect)),
        challengeId: value.challengeId,
        videoUrl: value.videoUrl
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _UserId;
    bio: string;
    referralCode: string;
    videoCount: bigint;
    coinBalance: bigint;
    city: string;
    createdAt: _Timestamp;
    rank: _Rank;
    referralCount: bigint;
    creatorName: string;
    district: string;
    totalVotesReceived: bigint;
    hasLegendTag: boolean;
    isUnlocked: boolean;
}): {
    id: UserId;
    bio: string;
    referralCode: string;
    videoCount: bigint;
    coinBalance: bigint;
    city: string;
    createdAt: Timestamp;
    rank: Rank;
    referralCount: bigint;
    creatorName: string;
    district: string;
    totalVotesReceived: bigint;
    hasLegendTag: boolean;
    isUnlocked: boolean;
} {
    return {
        id: value.id,
        bio: value.bio,
        referralCode: value.referralCode,
        videoCount: value.videoCount,
        coinBalance: value.coinBalance,
        city: value.city,
        createdAt: value.createdAt,
        rank: from_candid_Rank_n21(_uploadFile, _downloadFile, value.rank),
        referralCount: value.referralCount,
        creatorName: value.creatorName,
        district: value.district,
        totalVotesReceived: value.totalVotesReceived,
        hasLegendTag: value.hasLegendTag,
        isUnlocked: value.isUnlocked
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ChallengeId;
    title: string;
    endDate: _Timestamp;
    winnerId: [] | [_SubmissionId];
    category: _ChallengeCategory;
    rules: string;
    startDate: _Timestamp;
}): {
    id: ChallengeId;
    title: string;
    endDate: Timestamp;
    winnerId?: SubmissionId;
    category: ChallengeCategory;
    rules: string;
    startDate: Timestamp;
} {
    return {
        id: value.id,
        title: value.title,
        endDate: value.endDate,
        winnerId: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.winnerId)),
        category: from_candid_ChallengeCategory_n9(_uploadFile, _downloadFile, value.category),
        rules: value.rules,
        startDate: value.startDate
    };
}
function from_candid_variant_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Singing: null;
} | {
    Cooking: null;
} | {
    Gaming: null;
} | {
    Mimicry: null;
} | {
    Coding: null;
}): ChallengeCategory {
    return "Singing" in value ? ChallengeCategory.Singing : "Cooking" in value ? ChallengeCategory.Cooking : "Gaming" in value ? ChallengeCategory.Gaming : "Mimicry" in value ? ChallengeCategory.Mimicry : "Coding" in value ? ChallengeCategory.Coding : value;
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Professional: null;
} | {
    Cartoon: null;
} | {
    Cinematic: null;
}): VideoEffect {
    return "Professional" in value ? VideoEffect.Professional : "Cartoon" in value ? VideoEffect.Cartoon : "Cinematic" in value ? VideoEffect.Cinematic : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Gold: null;
} | {
    Platinum: null;
} | {
    Bronze: null;
} | {
    Silver: null;
}): Rank {
    return "Gold" in value ? Rank.Gold : "Platinum" in value ? Rank.Platinum : "Bronze" in value ? Rank.Bronze : "Silver" in value ? Rank.Silver : value;
}
function from_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Submission>): Array<Submission> {
    return value.map((x)=>from_candid_Submission_n13(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Challenge>): Array<Challenge> {
    return value.map((x)=>from_candid_Challenge_n6(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_User>): Array<User> {
    return value.map((x)=>from_candid_User_n19(_uploadFile, _downloadFile, x));
}
function to_candid_ChallengeCategory_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ChallengeCategory): _ChallengeCategory {
    return to_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function to_candid_CreateChallengeInput_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateChallengeInput): _CreateChallengeInput {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_RegisterInput_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RegisterInput): _RegisterInput {
    return to_candid_record_n28(_uploadFile, _downloadFile, value);
}
function to_candid_SubmitVideoInput_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SubmitVideoInput): _SubmitVideoInput {
    return to_candid_record_n30(_uploadFile, _downloadFile, value);
}
function to_candid_VideoEffect_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VideoEffect): _VideoEffect {
    return to_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bio: string;
    referralCode?: string;
    city: string;
    creatorName: string;
    district: string;
}): {
    bio: string;
    referralCode: [] | [string];
    city: string;
    creatorName: string;
    district: string;
} {
    return {
        bio: value.bio,
        referralCode: value.referralCode ? candid_some(value.referralCode) : candid_none(),
        city: value.city,
        creatorName: value.creatorName,
        district: value.district
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    endDate: Timestamp;
    category: ChallengeCategory;
    rules: string;
    startDate: Timestamp;
}): {
    title: string;
    endDate: _Timestamp;
    category: _ChallengeCategory;
    rules: string;
    startDate: _Timestamp;
} {
    return {
        title: value.title,
        endDate: value.endDate,
        category: to_candid_ChallengeCategory_n4(_uploadFile, _downloadFile, value.category),
        rules: value.rules,
        startDate: value.startDate
    };
}
function to_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    effect?: VideoEffect;
    challengeId: ChallengeId;
    videoUrl: string;
}): {
    effect: [] | [_VideoEffect];
    challengeId: _ChallengeId;
    videoUrl: string;
} {
    return {
        effect: value.effect ? candid_some(to_candid_VideoEffect_n31(_uploadFile, _downloadFile, value.effect)) : candid_none(),
        challengeId: value.challengeId,
        videoUrl: value.videoUrl
    };
}
function to_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VideoEffect): {
    Professional: null;
} | {
    Cartoon: null;
} | {
    Cinematic: null;
} {
    return value == VideoEffect.Professional ? {
        Professional: null
    } : value == VideoEffect.Cartoon ? {
        Cartoon: null
    } : value == VideoEffect.Cinematic ? {
        Cinematic: null
    } : value;
}
function to_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ChallengeCategory): {
    Singing: null;
} | {
    Cooking: null;
} | {
    Gaming: null;
} | {
    Mimicry: null;
} | {
    Coding: null;
} {
    return value == ChallengeCategory.Singing ? {
        Singing: null
    } : value == ChallengeCategory.Cooking ? {
        Cooking: null
    } : value == ChallengeCategory.Gaming ? {
        Gaming: null
    } : value == ChallengeCategory.Mimicry ? {
        Mimicry: null
    } : value == ChallengeCategory.Coding ? {
        Coding: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
